version: "3"

services:
    nginx:
        image: nginx
        volumes:
            - ./static:/data/static
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "9988:80"
        environment: 
            - NGINX_HOST=facevalcdn
            - NGINX_PORT=80
    postgres:
        image: postgres
        volumes: 
            - ./postgres/data:/var/lib/postgresql/data
        ports: 
            - "9029:5432"
        environment:
            - POSTGRES_PASSWORD=fv1234qwer